### ISSUE TITLE
Generate Setter question.

### ISSUE THREAD

**Issue by ctf0** [francodacosta/sublime-php-getters-setters#45]
thanx for the last update ,b4 that the plugin wasnt working but now it is so thanx.

- using the ex from the read me
```
class test {
	private $foo;
}
``` 
- when using generate getters & setters i get 
```
class test {

	private $foo;

    public function getFoo()
    {
        return $this->foo;
    }

    private function _setFoo($foo)
    {
        $this->foo = $foo;

        return $this;
    }
}
``` 
does "setFoo" suppose to have the ( _ ) ???

also am having the same problem as this https://github.com/francodacosta/sublime-php-getters-setters/issues/20 ,the problem is with the "PHP Generate Setter"  but "Generate Setter for ..." is working as it should.

btw is there a way to config how the output would look ? , so instead of
```
$this->foo = $foo;

return $this;
``` 
it would be
```
return $this->foo = $foo;
```

**Comment by regisnew** [comment]
I used
```json
{
"ignore_visibility" : true
}
```
It works.

**Comment by ioncube** [comment]
@francodacosta @regisnew ignore_visibility - the old undocumented feature trick :)  Thanks for the useful plugin, definitely a time saver.

**Comment by ctf0** [comment]
@francodacosta that worked ,thank you
