### ISSUE TITLE
disabled menu items

### ISSUE THREAD

**Issue by unstoppablecarl** [francodacosta/sublime-php-getters-setters#6]
I am just starting to use ST2 so it might just be my lack of experience with it. I installed the package with the package manager. I created a test.php file with your example code and see the menu options when I right click and goto Getters and Setters but all the options are disabled. When I goto tools > PHP Getters and Setters I get an input dialog that says PHP: Generate. What am I missing?

**Comment by hardik-satasiya** [comment]
just try this out : 

i have found the solution in my case language detection was : **PHP.tmLanguage**

but in plugin it was checking 

line : 406
https://github.com/francodacosta/sublime-php-getters-setters/blob/master/php-getter-setter.py

`return re.search(".*\PHP.sublime-syntax", self.view.settings().get('syntax')) is not None`

so it was **PHP.sublime-syntax**

i have just replaced **PHP.sublime-syntax** with new one **PHP.tmLanguage** which i have find using debug.

and it started working :+1:
